export const columns = [
   { nombre: 'Nombre', uid: 'nombre' },
   { nombre: 'Fecha nacimiento', uid: 'fecha' },
   { nombre: 'Carnet', uid: 'carnet' },
   { nombre: 'Sexo', uid: 'sexo' },
   { nombre: 'Email', uid: 'email' },
   { nombre: 'Grupo Sanguineo', uid: 'grupoSanguineo' },
   { nombre: 'Alergia', uid: 'alergia' },
   { nombre: 'Antecedentes Medico', uid: 'antesedentesMedico' },
   { nombre: 'Colegio', uid: 'colegio' },
   { nombre: 'grado', uid: 'grado' },
   { nombre: 'Estado', uid: 'estado' },
   { nombre: 'ACTIONS', uid: 'actions' },
];
export const users = [
   {
      id: 1,
      nombre: 'kevin delgadillo salazar',
      fecha: '31/12/2024',
      carnet: '6589125',
      sexo: 'masculino',
      email: 'tony.reichert@example.com',
      grupoSanguineo: 'ORH+',
      alergia: 'al cambio de clima',
      antesedentesMedico: 'se quebro la muñeca el 2023',
      colegio: 'Juan Pablo II',
      grado: '3ro secundaria',
      estado: 'debe',
      avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
   },
   {
      id: 2,
      nombre: 'juan suarez salazar',
      fecha: '1/12/1090',
      carnet: '6545125',
      sexo: 'masculino',
      email: 'tony.reichert@example.com',
      grupoSanguineo: 'ORH+',
      alergia: null,
      antesedentesMedico: 'se quebro la pierna el 2020',
      colegio: null,
      grado: null,
      estado: 'pagado',
      avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
   },
   {
      id: 3,
      nombre: 'antonella sandobal delgadillo',
      fecha: '1/12/1090',
      carnet: '6545125',
      sexo: 'masculino',
      email: 'tony.reichert@example.com',
      grupoSanguineo: 'ORH+',
      alergia: null,
      antesedentesMedico: 'se quebro la pierna el 2020',
      colegio: null,
      grado: null,
      estado: 'pagado',
      avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
   },
];
